my:
   greeting: Hello World
   list: 
      values: One,Two,Three
      
app:
   name: My app
   description: Welcome to ${app.name}     
   
management:
   endpoints:
      web:
         exposure:
            include: "*"
            
spring:
  cloud:
    config:
      uri:
      - http://localhost:8080
  profiles:
      active: test   
  application:
    name: spring-cloud-config-client